### ISSUE TITLE
avoid format! in the `map` hot path

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/sandboxfs#111]
My product team is finally porting some C++ projects to Bazel, and we're using sandboxfs to reduce Bazel sandbox overhead of C++ compile actions which pull in thousands of headers from Boost. We were surprised to find out that tmpfs (`--sandbox_base=/dev/shm`) performed better than sandboxfs ([thread](https://groups.google.com/forum/#!topic/bazel-discuss/VT15soOI-ZA)). Profling sandboxfs, a flame graph revealed >50% of CPU time spent in `create_sandbox`, with the bulk of that in `apply_mapping`.

![sandboxfs-1590698321](https://user-images.githubusercontent.com/39353016/83281392-0b08f180-a1a6-11ea-9007-9e77be39bde9.png)

A surprising amount of time in `apply_mapping` was in Rust's string formatting code, which I tracked to here: https://github.com/bazelbuild/sandboxfs/blob/sandboxfs-0.2.0/src/nodes/dir.rs#L537-L543

By replacing the `format!()` macro with a static string, string formatting dropped out of `apply_mapping`'s call graph and reduced `create_sandbox`'s share of CPU time to 37%.

![sandboxfs-1590700702](https://user-images.githubusercontent.com/39353016/83281409-0e9c7880-a1a6-11ea-8177-8ac825d359a9.png)

The tradeoff is that the error message, if ever reported to the user, no longer includes the path that we failed to `stat`. I'm a total Rust noob, so I don't yet know if there's a way to either turn this into a simple/cheap string concatenation or to lazily evaluate the format operation only upon failure.

**Comment by jmmv** [comment]
Oh, that's awesome. Thanks for the diagnostic!

I think the idiomatic way to do this in Rust is to replace the call to `context` with another function that takes a lambda and generates the right result value. This delays the computation until necessary, and is what's done for all standard types like `Result` and `Option` (e.g. compare `and` with `and_then`). And it looks like `with_context` is what this does.

I've pushed #112 with this change. Is there any chance you could measure it before I merge it?

Also, how did you do the profiling? So far, I've been relying on pprof and hadn't seen this issue...

**Comment by beasleyr-vmw** [comment]
Wow, that was quick. Rad.

Here's the [flame graph](https://github.com/brendangregg/FlameGraph) with your change applied:

![sandboxfs-1590777081](https://user-images.githubusercontent.com/39353016/83294370-334f1b00-a1bb-11ea-8713-e3c52e3d05ec.png)

`create_sandbox` accumulates only ~35% of the samples, so this is a neat (50-35=) ~15% reduction from before. (The measured improvement in the initial report was only ~13% -- 50-37.)

> Also, how did you do the profiling? So far, I've been relying on pprof and hadn't seen this issue...

- CentOS 7.6 VM w/ 32 vCPUs and 128GiB of RAM
- Bazel 3.1.0
    - `--experimental_sandboxfs_path=.../sandboxfs.wrapper`
    - `sandboxfs.wrapper` is a simple bash shim containing `exec sandboxfs.real --cpu_profile sandboxfs-%(date +%s).profile "$@"`.
    - Workload consists of ~22K actions.
         - 21K "Symlinking virtual headers"
         - 1K `CppCompile`, 60 `CppLink`
         - ~1.4GiB of captured Bazel->sandboxfs JSON messages.
- sandboxfs 0.2.0
    - Built with `--release` and `--features=cpu_profiling`.

Flame graph generated w/ `pprof --collapsed sandboxfs.real sandboxfs-X.profile | c++filt | rust-unmangle | flamegraph.pl`.

Thanks for picking this one up!

**Comment by jmmv** [comment]
Ah OK, so you were using the pprof support already :) Great! I'll give that a try at some point given that sandboxfs hasn't achieved the level of speedups that I think it could...

Thanks for confirming! I fixed the measurements in the change description and the news entry and will merge once they finish testing.
