### ISSUE TITLE
hanwen/go-fuse

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/sandboxfs#58]
Just out of curiosity, have you considered to use https://github.com/hanwen/go-fuse for FUSE go-binding? We are using that extensively for a similar use case and didn't notice any significant performance issue.

**Comment by jmmv** [comment]
I had, but that library uses the path-based FUSE API (which I find unfortunate) and using it at this point would involve a full rewrite of the current implementation anyway.

Regardless, the performance issues of the Go version of sandboxfs come primarily from the use of parallelism in the Bazil FUSE libraries. Disabling all forms of parallelism increases performance significantly (bringing it to almost the levels of the Rust code)... but that makes me fear that adding parallelism later, even with hanwen/go-fuse, would result in similar poor results.
