### ISSUE TITLE
Running 'sandboxfs' with no arguments should show the usage message

### ISSUE THREAD

**Issue by rupertks** [bazelbuild/sandboxfs#7]
Instead of just telling users to run ```sandboxfs --help``` to see the usage message

**Comment by jmmv** [comment]
Nope. I hate that behavior (and most well-behaved tools agree, from the simple like "cp" to the more complex like "svn"). My thoughts at: http://julio.meroh.net/2013/08/cli-design-requesting-and-offering-help.html
