### ISSUE TITLE
Reach outside of sandboxfs

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/sandboxfs#79]
I am just debugging a nodejs rule that seems to behave in a non-hermetic way (see https://github.com/bazelbuild/rules_nodejs/pull/612 if you are interested in background) and I thought sandboxfs can help me there with greater hermeticity, but the rule still behaves exactly the same way. So my question, given an absolute path is it still possible to access the filesystem outside of sandboxfs? And if so is there some way of blocking this?

**Comment by jmmv** [comment]
Yes, it's possible to reach absolute paths because sandboxfs does not actually do sandboxing. Grr, the name of this project is wrong...

See Bazel's `--sandbox_block_path`, which may help you.

**Comment by Globegitter** [comment]
I guess indirectly it helps, at least in the Bazel case, by not using symlinks anymore but yes names are hard. And thanks for the pointer to the flag.
