### ISSUE TITLE
sandboxfs hangs when trying to mount

### ISSUE THREAD

**Issue by egechir** [bazelbuild/sandboxfs#84]
Hello ,

I am trying to build a hello-world c++ program using the sandboxfs.
My OS is RHEL 7.3 with {kernel 3.10 , libfuse.so.2.9.2} and the user has sudo access.
When I build with the command line **"bazel  build  //main:hello-world --experimental_sandboxfs_path=/home/egechir/install_dir/sandboxfs/bin/sandboxfs --experimental_use_sandboxfs"** , I get  [these](https://github.com/bazelbuild/sandboxfs/files/3556489/sandboxFsInvokedbyBazel.log) log messages. In this case, Bazel invokes sandboxfs to mount on a certain mount point. 
When I execute  sandboxfs  with the  command **"/home/egechir/install_dir/sandboxfs/bin/sandboxfs   --allow=self ."**  ,  I get [these](https://github.com/bazelbuild/sandboxfs/files/3556506/sandboxFsStandalone.log) log messages.

I found these two log messages interesting
**DEBUG 2019-08-29T15:48:30Z: fuse::request: INIT(1)   kernel: ABI 7.22, flags 0xf7fb, max readahead 131072
DEBUG 2019-08-29T15:48:30Z: fuse::request: INIT(1) response: ABI 7.8, flags 0x1, max readahead 131072, max write 16777216**

My interpretation of above is that the rust-fuse receives the **FUSE_INIT (kernel ABI 7.22)** messaget from kernel driver  and rust-fuse replies with **FUSE_INIT( ABI 7.8)**. Then the  kernel driver has either replied with a FUSE protocol message that it has not yet implemented in rust-fuse or the kernel replied nothing. In both those logs, one can see that when the sandboxfs process is either terminated or interrupted, the rust-fuse receives the **FUSE_FORGET** message from the kernel. 

Does anyone know why the communication between sandboxfs and kernel stops when trying to mount ?
Are the ABIs of rust-fuse and kernel incompatible ?
Any advice on how to go forward ?

**Comment by philwo** [comment]
@jmmv Any idea?

**Comment by egechir** [comment]
@philwo , @jmmv , 
We have progressed beyond this problem and therefore this can be closed.
Thank you for the support.
