### ISSUE TITLE
Files become inaccessible when their parent directory is moved

### ISSUE THREAD

**Issue by tkuosmanen** [bazelbuild/sandboxfs#94]
This issue affects the latest top of tree (855834e). Files become inaccessible when their parent directory is moved. Below is an error case that can be reliably reproduced with a build from 855834e:

Terminal 1:
```
mkdir -p ./out ./new_sandbox
sandboxfs --mapping=ro:/:/ --mapping=rw:/out:$PWD/out ./new_sandbox
...
```

Terminal 2:
```
$ cd new_sandbox/out/
$ mkdir target to_be_moved
$ echo dummy > to_be_moved/dummy.txt
$ mv to_be_moved/ target/
$ echo "contents of target:" && ls -l target && echo "contents of target/to_be_moved:" && ls -l target/to_be_moved
contents of target:
total 0
drwxrwxr-x 2 tkuosmanen tkuosmanen 2 Feb  7 14:18 to_be_moved
contents of target/to_be_moved:
ls: cannot access 'target/to_be_moved/dummy.txt': No such file or directory
total 0
-????????? ? ? ? ?            ? dummy.txt
```

File `target/to_be_moved/dummy.txt` is stuck in a bad state. 

This was run on Ubuntu 16.04 workstation with 4.4.0-133-generic kernel and ext4 root file system.

**Comment by jmmv** [comment]
Yikes, of course this is broken. When we move a directory, we update the underlying path for that directory... but not for any of the files it contains. So those files continue to point to their previous on-disk locations, which of course are gone after the move, and thus we get into this invalid state.

Fixing this in the current design means that `rename` will become a linear operation on the (transitive) contents of the moved directory (though we only have to update in-memory state so maybe it's not that bad).

**Comment by jmmv** [comment]
Ah, the fix was much easier than I thought. Done!

Please keep the bug fixes coming!
