### ISSUE TITLE
Removing a file causes sandboxfs to crash

### ISSUE THREAD

**Issue by tkuosmanen** [bazelbuild/sandboxfs#98]
With a build of the latest top of tree (ef7ff49), sandboxfs crashes when removing a file. The parent directory of the file needs to be moved first and then removing the file hits some sort of cache corruption.

Terminal 1:
```
$ mkdir -p ./out ./new_sandbox
$ RUST_LOG=debug sandboxfs --mapping=ro:/:/ --mapping=rw:/out:$PWD/out ./new_sandbox

...

DEBUG 2020-02-11T08:20:06Z: fuse::request: UNLINK(24) parent 0x0000000000000004, name "dummy.txt"
thread 'main' panicked at 'Tried to delete unknown path from the cache', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
 WARN 2020-02-11T08:20:06Z: fuse::reply: Reply not sent for operation 24, replying with I/O error
DEBUG 2020-02-11T08:20:06Z: sandboxfs::concurrent: Closing ShareableFile with fd 3
 INFO 2020-02-11T08:20:06Z: fuse::session: Unmounted /home/tkuosmanen/new_sandbox
 INFO 2020-02-11T08:20:06Z: sandboxfs::reconfig: Reached end of reconfiguration input; file system mappings are now frozen
```

Terminal 2:
```
$ cd new_sandbox/out/
$ mkdir target to_be_moved
$ echo dummy > to_be_moved/dummy.txt
$ mv to_be_moved target
$ rm target/to_be_moved/dummy.txt
rm: cannot remove 'target/to_be_moved/dummy.txt': Input/output error
```

This was run on Ubuntu 16.04 workstation with 4.4.0-133-generic kernel and ext4 root file system.

**Comment by jmmv** [comment]
Right... my fix was too "quick" yesterday. Realized this morning when I woke up that I had forgotten to update the cache contents. (Why? Because I have a local change to just remove that cache and hadn't hit this.)

**Comment by jmmv** [comment]
Alright... should be fixed. Let's see what comes up next... Sorry for getting it wrong the first time!

**Comment by tkuosmanen** [comment]
No problem, thanks for ironing out the bugs!
